Repository TheRealHoko/config-editor, pull requests merged in 2024-04, with the labels that each got.

#3 add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#8 create kickoff
  docs/Kickoff.md
  docs/assets/Inspiration.png
  docs/assets/PoC.svg
Labels: documentation, help wanted

#11 Feature/ci
  .github/workflows/node.js.yml
Labels: enhancement

#12 Update LICENSE
  LICENSE
Labels: documentation

#19 adding tests
  config-editor/src/App.test.tsx
Labels: enhancement

#10 add contributing and readme redirect to it
  CONTRIBUTING.md
  README.md
Labels: documentation
